apiVersion: phenix.sandia.gov/v1
kind: Experiment
metadata:
  name: caldera-training
spec:
  scenario:
    apps:
    - name: tap
      metadata:
        taps:
        - bridge: phenix
          vlan: hack
          ip: 10.0.40.254/24
          externalAccess:
            enabled: true
    - name: caldera
      hosts:
      - hostname: pwn-win
        metadata:
          server: caldera:0
    - name: scorch
      metadata:
        components:
        - name: dnp3
          type: caldera
          metadata:
            server: caldera
            adversary: OT DNP3 Demonstration
            facts: OT DNP3 Demonstration
        runs:
        - start:
          - dnp3
  topology:
    nodes:
    - general:
        hostname: caldera
      annotations:
        phenix/startup-autotunnel:
        - 5901:localhost:vnc
        - 8888:localhost:8888
      hardware:
        drives:
        - image: caldera.qc2
        os_type: linux
        memory: 4096
        vcpus: 2
      injections:
      - src: /phenix/projects/caldera-training/injects/caldera
        dst: /opt
      - src: /phenix/projects/caldera-training/injects/firefox-autostart.desktop
        dst: /root/.config/autostart/Caldera.desktop
      - src: /phenix/projects/caldera-training/injects/firefox-bookmark.json
        dst: /etc/firefox/policies/policies.json
      network:
        interfaces:
        - address: 10.0.40.10
          mask: 24
          gateway: 10.0.40.254
          name: IF0
          proto: static
          type: ethernet
          vlan: hack
      type: VirtualMachine
    - general:
        hostname: pwn-win
      annotations:
        includes-phenix-startup: true
        phenix/windows-rearm: true
      hardware:
        drives:
        - image: win-10.qc2
        os_type: windows
        memory: 4096
        vcpus: 2
      injections:
      - src: /phenix/projects/caldera-training/injects/Disable-WindowsFirewall.ps1
        dst: /phenix/startup/50-disable-firewall.ps1
      network:
        interfaces:
        - address: 10.0.40.200
          mask: 24
          gateway: 10.0.40.254
          name: IF0
          proto: static
          type: ethernet
          vlan: hack
      type: VirtualMachine
    - general:
        hostname: ot-sim
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
        memory: 1024
        vcpus: 1
      injections:
      - src: /phenix/projects/caldera-training/injects/ot-sim.xml
        dst: /etc/ot-sim/config.xml
      network:
        interfaces:
        - address: 10.0.40.100
          mask: 24
          gateway: 10.0.40.254
          name: IF0
          proto: static
          type: ethernet
          vlan: hack
      type: VirtualMachine
