apiVersion: phenix.sandia.gov/v1
kind: Experiment
metadata:
  name: wind-turbine
spec:
  scenario:
    apps:
    - name: wind-turbine
      metadata:
        ground-truth-module:
          elastic:
            endpoint: http://192.168.100.250:9200
            index-base-name: wind-turbine
        templates:
          default:
            main-controller:
              turbine:
                type: E-126/4200
                hubHeight: 135
                roughnessLength: 0.15
              logic:
                speedTag: speed.high
                directionTag: dir.high
                directionError: 0.04
              node-red:
                flow: /phenix/projects/wind-turbine/injects/node-red.json
                endpoint:
                  host: 0.0.0.0
                  port: 1880
                auth:
                  editor:
                    user: admin
                    pass: admin
                  ui:
                    user: foo
                    pass: bar
              weather:
                columns:
                - name: wind_speed
                  tags:
                  - name: speed.high
                    height: 58.2
                  - name: speed.med
                    height: 36.6
                  - name: speed.low
                    height: 15.0
                - name: temperature
                  tags:
                  - name: temp.high
                    height: 58.2
                  - name: temp.low
                    height: 3.0
                - name: pressure
                  tags:
                  - name: pressure
                    height: 0.0
            anemometer:
              weather:
                replayData: /phenix/projects/wind-turbine/injects/weather.csv
                columns:
                - name: Windspeed 58.2m
                  tag: speed.high
                - name: Windspeed 36.6m
                  tag: speed.med
                - name: Windspeed 15.0m
                  tag: speed.low
                - name: Wind Direction 58.2m
                  tag: dir.high
                - name: Wind Direction 36.6m
                  tag: dir.med
                - name: Wind Direction 15.0m
                  tag: dir.low
                - name: Temperature 58.2m
                  tag: temp.high
                - name: Temperature 3.0m
                  tag: temp.low
                - name: Barometric Pressure
                  tag: pressure
            yaw-controller:
              yaw:
                initialPosition: 0
                degreePerSecond: 0.1
      hosts:
      - hostname: "(.*-(.*))-main-controller"
        metadata:
          type: main-controller
          template: default
          controllers:
            anemometer: "$1-signal-converter"
            yaw: "$1-yaw-controller"
            blades:
            - "$1-blade-1"
            - "$1-blade-2"
            - "$1-blade-3"
          ground-truth-module:
            elastic:
              labels:
                turbine: "$1"
  topology:
    nodes:
    - general:
        hostname: grafana
      hardware:
        drives:
        - image: grafana.qc2
        memory: 4096
        os_type: linux
        vcpus: 2
      injections:
      - src: /phenix/projects/wind-turbine/injects/grafana/elasticsearch.yml
        dst: /etc/elasticsearch/elasticsearch.yml
      - src: /phenix/projects/wind-turbine/injects/grafana/grafana.ini
        dst: /etc/grafana/grafana.ini
      - src: /phenix/projects/wind-turbine/injects/grafana/elastic-data-source.yml
        dst: /etc/grafana/provisioning/datasources/elastic.yml
      - src: /phenix/projects/wind-turbine/injects/grafana/dashboards.yml
        dst: /etc/grafana/provisioning/dashboards/dashboards.yml
      - src: /phenix/projects/wind-turbine/injects/grafana/turbine-dashboard.json
        dst: /var/lib/grafana/dashboards/turbine-dashboard.json
      network:
        interfaces:
        - address: 192.168.100.250
          gateway: 192.168.100.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: ot
      type: VirtualMachine
    - general:
        hostname: wtg-1-main-controller
      annotations:
        phenix/startup-autotunnel:
        - 1880:localhost:1880
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 192.168.100.1
          gateway: 192.168.100.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: ot
        - address: 1.1.1.254
          mask: 24
          name: IF1
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
    - general:
        hostname: wtg-1-yaw-controller
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 1.1.1.11
          gateway: 1.1.1.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
    - general:
        hostname: wtg-1-signal-converter
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 1.1.1.21
          gateway: 1.1.1.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
    - general:
        hostname: wtg-1-blade-1
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 1.1.1.31
          gateway: 1.1.1.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
    - general:
        hostname: wtg-1-blade-2
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 1.1.1.32
          gateway: 1.1.1.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
    - general:
        hostname: wtg-1-blade-3
      hardware:
        drives:
        - image: ot-sim.qc2
        os_type: linux
      network:
        interfaces:
        - address: 1.1.1.33
          gateway: 1.1.1.254
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: turbine
      type: VirtualMachine
